baseURL = 'https://nsrahmad.github.io/'
languageCode = 'en-us'
title = "Nisar's Blog"
paginate = 5
theme = 'PaperMod'
enableInlineShortcodes = true
enableEmoji = true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
env = 'production'
author = 'Nisar Ahmad'
ShowReadingTime = true
ShowShareButtons = true
ShowToc = true
ShowRssButtonInSectionTermList = true

[languages.en]
languageName = 'English'
weight = 1

[languages.en.taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "RSS"
url = "index.xml"


